// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef i_current_2_h
#define i_current_2_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *main_panel;
#include <FL/Fl_Progress.H>
extern Fl_Progress *ProgBar;
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
extern Fl_Group *group_input;
extern Fl_Group *input_panel;
#include <FL/Fl_Box.H>
extern Fl_Box *box_source;
extern Fl_Box *box_sink;
extern Fl_Box *box_substrate;
extern Fl_Box *box_material1;
extern Fl_Box *box_material2;
extern Fl_Box *box_material3;
extern Fl_Box *box_material4;
#include <FL/Fl_Button.H>
extern Fl_Button *btn_open_image;
extern Fl_Button *btn_check;
extern Fl_Button *btn_open_cfg;
extern Fl_Button *btn_save_cfg;
extern Fl_Button *pick_source;
extern Fl_Button *pick_sink;
extern Fl_Button *pick_substr;
extern Fl_Button *pick_material1;
#include <FL/Fl_Choice.H>
extern Fl_Choice *choice_material_1;
extern Fl_Button *pick_material2;
extern Fl_Button *pick_material3;
extern Fl_Button *pick_material4;
#include "Fl_Image_Display.H"
extern Fl_Image_Display *copper_plane_s;
extern Fl_Group *group_analyze;
extern Fl_Button *btn_analyze;
extern Fl_Button *btn_show;
#include <FL/Fl_Value_Input.H>
extern Fl_Value_Input *pixel_x_umeters;
extern Fl_Choice *choice_cu_thickness;
#include <FL/Fl_Spinner.H>
extern Fl_Spinner *spinner_threads;
extern Fl_Button *btn_save_log;
extern Fl_Button *btn_qsave_log;
extern Fl_Value_Input *source_voltage;
#include <FL/Fl_Value_Output.H>
extern Fl_Value_Output *initial_temp_out;
#include <FL/Fl_Dial.H>
extern Fl_Dial *initial_temp;
#include <FL/Fl_Browser.H>
extern Fl_Browser *main_log;
extern Fl_Group *group_output;
extern Fl_Choice *choice_colormap;
extern Fl_Choice *choice_show;
extern Fl_Button *btn_save_image;
extern Fl_Button *btn_save_data;
extern Fl_Value_Output *out_R;
extern Fl_Value_Output *out_G;
extern Fl_Value_Output *out_B;
extern Fl_Value_Output *out_I;
extern Fl_Value_Output *out_Ix;
extern Fl_Value_Output *out_Iy;
extern Fl_Value_Output *out_V;
extern Fl_Image_Display *current_density_plot_s;
Fl_Double_Window* make_window();
extern Fl_Menu_Item menu_[];
extern Fl_Menu_Item menu_choice_colormap[];
extern Fl_Menu_Item menu_choice_show[];
extern Fl_Box *fltk_version_box;
extern Fl_Button *about_close;
Fl_Double_Window* make_about_window();
extern Fl_Value_Input *input_max_iter;
extern Fl_Value_Input *pixel_y_umeters;
extern Fl_Value_Input *input_cutoff;
Fl_Double_Window* make_config_window();
extern Fl_Value_Input *r_source_d;
#include <FL/Fl_Output.H>
extern Fl_Output *r_source_h;
extern Fl_Value_Input *g_source_d;
extern Fl_Output *g_source_h;
extern Fl_Value_Input *b_source_d;
extern Fl_Output *b_source_h;
Fl_Double_Window* make_edit_source_window();
extern Fl_Value_Input *r_sink_d;
extern Fl_Output *r_sink_h;
extern Fl_Value_Input *g_sink_d;
extern Fl_Output *g_sink_h;
extern Fl_Value_Input *b_sink_d;
extern Fl_Output *b_sink_h;
Fl_Double_Window* make_edit_sink_window();
extern Fl_Value_Input *r_substrate_d;
extern Fl_Output *r_substrate_h;
extern Fl_Value_Input *g_substrate_d;
extern Fl_Output *g_substrate_h;
extern Fl_Value_Input *b_substrate_d;
extern Fl_Output *b_substrate_h;
Fl_Double_Window* make_edit_substr_window();
extern Fl_Double_Window *panel_material1;
extern Fl_Value_Input *r_material1_d;
extern Fl_Output *r_material1_h;
extern Fl_Value_Input *g_material1_d;
extern Fl_Output *g_material1_h;
extern Fl_Value_Input *b_material1_d;
extern Fl_Output *b_material1_h;
extern Fl_Value_Input *conductance_m1;
Fl_Double_Window* make_edit_m1_window();
extern Fl_Value_Input *r_material4_d;
extern Fl_Output *r_material4_h;
extern Fl_Value_Input *g_material4_d;
extern Fl_Output *g_material4_h;
extern Fl_Value_Input *b_material4_d;
extern Fl_Output *b_material4_h;
extern Fl_Value_Input *conductance_m4;
extern Fl_Value_Input *r_material3_d;
extern Fl_Output *r_material3_h;
extern Fl_Value_Input *g_material3_d;
extern Fl_Output *g_material3_h;
extern Fl_Value_Input *b_material3_d;
extern Fl_Output *b_material3_h;
extern Fl_Value_Input *conductance_m3;
extern Fl_Value_Input *r_material2_d;
extern Fl_Output *r_material2_h;
extern Fl_Value_Input *g_material2_d;
extern Fl_Output *g_material2_h;
extern Fl_Value_Input *b_material2_d;
extern Fl_Output *b_material2_h;
extern Fl_Value_Input *conductance_m2;
extern Fl_Choice *choice_material_4;
extern Fl_Choice *choice_material_3;
extern Fl_Choice *choice_material_2;
Fl_Double_Window* make_edit_additional_window();
extern Fl_Double_Window* config_window;
extern Fl_Double_Window* about_window;
extern Fl_Double_Window* main_window;
extern Fl_Double_Window* source_edit_window;
extern Fl_Double_Window* sink_edit_window;
extern Fl_Double_Window* substrate_edit_window;
extern Fl_Double_Window* material1_edit_window;
extern Fl_Double_Window* additional_edit_window;
#endif
